### ISSUE TITLE
Should I be able to get the example up and running?

### ISSUE THREAD

**Issue by creimers** [jrief/django-shop#12]
Should the example be in a working state?

Running ``./manage.py syncdb`` presents me with:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/creimers/Projekte/jrief_shop/example/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/creimers/Projekte/jrief_shop/example/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/creimers/Projekte/jrief_shop/example/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/creimers/Projekte/jrief_shop/example/env/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/creimers/Projekte/jrief_shop/example/env/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/creimers/Projekte/jrief_shop/example/env/lib/python2.7/site-packages/django_select2/__init__.py", line 111, in <module>
    from .fields import Select2ChoiceField, Select2MultipleChoiceField, HeavySelect2ChoiceField, \
  File "/Users/creimers/Projekte/jrief_shop/example/env/lib/python2.7/site-packages/django_select2/fields.py", line 812, in <module>
    class AutoModelSelect2Field(ModelResultJsonMixin, AutoViewFieldMixin, HeavyModelSelect2ChoiceField):
  File "/Users/creimers/Projekte/jrief_shop/example/env/lib/python2.7/site-packages/django_select2/fields.py", line 301, in __new__
    return type.__new__(cls, name, bases, dct)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by febsn** [comment]
AFAIK, the example is not in a working state at the moment. As documentation is not up to date, expect a lot of code reading. As a start, as you are trying to syncdb, take a look at how most models are materialized in this fork: https://github.com/jrief/django-shop/blob/0.3.0.dev/docs/deferred-models.rst
If you want to contribute to code or documentation, let us know! Otherwise, check back for updates from time to time.

**Comment by creimers** [comment]
@febsn Yes, I am interested in contributing. You can email me at creimers@byteyard.de.

**Comment by creimers** [comment]
@febsn I'm still interested. How shall we go about it? Do you e.g. have a to do list?

**Comment by jrief** [comment]
Yes one big issue to solve is this one: https://github.com/edoburu/django-parler/issues/51
It is independent of the current shop software, but it inhibits me to migrate to Django-1.7/1.8
Apparently all tests pass with Python-3, but not with Py-2.7. Details here: https://travis-ci.org/edoburu/django-parler/builds/64733366

If we can fix that, great. Otherwise try to create a set of simple models (without adding parler as dependency) and file a bug on Django's own issue tracker. 
IMHO this bug is inside Django, not Parler.

**Comment by jrief** [comment]
@creimers Following the instructions in docs/quickstart.rst should allow you to get a django-shop demo up an running in < 5 minutes.

**Comment by creimers** [comment]
@jrief Thank you for the update. Can't wait to check it out!

**Comment by jrief** [comment]
Feedback is welcomed!
